# Generated by Django 5.2.10 on 2026-01-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icp_last_reviewed',
            field=models.DateTimeField(blank=True, help_text='Last time the user reviewed/confirmed their ICP', null=True),
        ),
    ]
