# Generated by Django 5.2.10 on 2026-01-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sequence_position",
                    models.IntegerField(
                        help_text="Position in the GEX 4-email sequence (1-4)"
                    ),
                ),
                ("subject_line", models.CharField(max_length=255)),
                (
                    "body_template",
                    models.TextField(
                        help_text="Email body with {{placeholders}} for personalization"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of placeholder variable names used in the template",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cold_outreach", "Cold Outreach"),
                            ("jv_pitch", "JV Pitch"),
                            ("follow_up", "Follow Up"),
                            ("breakup", "Breakup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Outreach Template",
                "verbose_name_plural": "Outreach Templates",
                "ordering": ["sequence_position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_profiles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="outreach_campaigns",
                        to="matching.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="outreach.outreachtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outreach Campaign",
                "verbose_name_plural": "Outreach Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("pain_solution", "Pain Solution"),
                            ("insight_share", "Insight Share"),
                            ("mutual_benefit", "Mutual Benefit"),
                            ("social_proof", "Social Proof"),
                            ("curiosity_hook", "Curiosity Hook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pain_point_addressed", models.TextField()),
                ("value_offered", models.TextField()),
                ("call_to_action", models.TextField()),
                ("full_message", models.TextField()),
                ("personalization_data", models.JSONField(blank=True, null=True)),
                ("ai_model_used", models.CharField(max_length=50)),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Quality score based on 7-criterion rubric (0-100)",
                        null=True,
                    ),
                ),
                ("is_template", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pvps",
                        to="matching.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PVP",
                "verbose_name_plural": "PVPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutreachActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email_sent", "Email Sent"),
                            ("email_opened", "Email Opened"),
                            ("link_clicked", "Link Clicked"),
                            ("replied", "Replied"),
                            ("meeting_booked", "Meeting Booked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_activities",
                        to="matching.profile",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="outreach.outreachcampaign",
                    ),
                ),
                (
                    "pvp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="outreach.pvp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outreach Activity",
                "verbose_name_plural": "Outreach Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
