# Generated by Django 5.2.10 on 2026-01-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvp',
            name='supabase_profile_id',
            field=models.UUIDField(blank=True, help_text='UUID of the SupabaseProfile this PVP was generated for', null=True),
        ),
    ]
