# Generated by Django 5.2.10 on 2026-01-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_supabasematch_supabaseprofile'),
        ('outreach', '0002_add_supabase_profile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence_type', models.CharField(choices=[('lookalike', 'Lookalike Campaign'), ('trigger', 'Trigger-Based'), ('creative_ideas', 'Creative Ideas'), ('poke_bear', 'Poke the Bear'), ('super_short', 'Super Short')], default='lookalike', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Send'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('ai_personalization', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.supabasematch')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.supabaseprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outreach Sequence',
                'verbose_name_plural': 'Outreach Sequences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_number', models.IntegerField()),
                ('is_threaded', models.BooleanField(default=False)),
                ('subject_line', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='outreach.outreachsequence')),
            ],
            options={
                'verbose_name': 'Outreach Email',
                'verbose_name_plural': 'Outreach Emails',
                'ordering': ['email_number'],
                'unique_together': {('sequence', 'email_number')},
            },
        ),
    ]
