# Generated by Django 5.2.9 on 2026-03-05 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0023_evaluationbatch_completion_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_address', models.EmailField(max_length=254, unique=True)),
                ('signup_url', models.TextField(blank=True)),
                ('esp_detected', models.CharField(blank=True, max_length=50)),
                ('discovery_method', models.CharField(choices=[('crawl4ai_form', 'Crawl4AI Form'), ('manual', 'Manual'), ('esp_api', 'ESP API'), ('headless', 'Headless Browser')], default='crawl4ai_form', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('pending_confirm', 'Pending Confirmation'), ('unsubscribed', 'Unsubscribed'), ('bouncing', 'Bouncing'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_email_received_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails_received', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_subscriptions', to='matching.supabaseprofile')),
            ],
            options={
                'verbose_name': 'Monitored Subscription',
                'verbose_name_plural': 'Monitored Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('emails_sent', models.IntegerField(default=0)),
                ('avg_emails_per_week', models.FloatField(default=0.0)),
                ('promotional_emails', models.IntegerField(default=0)),
                ('own_product_emails', models.IntegerField(default=0)),
                ('content_only_emails', models.IntegerField(default=0)),
                ('promotion_ratio', models.FloatField(default=0.0)),
                ('unique_partners_promoted', models.IntegerField(default=0)),
                ('partners_promoted', models.JSONField(default=list)),
                ('promotion_types', models.JSONField(default=dict)),
                ('mailing_activity_score', models.FloatField(default=0.0)),
                ('promotion_willingness_score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_activity_summaries', to='matching.supabaseprofile')),
            ],
            options={
                'verbose_name': 'Email Activity Summary',
                'verbose_name_plural': 'Email Activity Summaries',
                'ordering': ['-month'],
                'unique_together': {('profile', 'month')},
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=100, unique=True)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField()),
                ('received_at', models.DateTimeField(db_index=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('links_extracted', models.JSONField(default=list)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_monitor.monitoredsubscription')),
            ],
            options={
                'verbose_name': 'Inbound Email',
                'verbose_name_plural': 'Inbound Emails',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['subscription', 'received_at'], name='email_monit_subscri_743e65_idx')],
            },
        ),
    ]
