# Generated by Django 5.2.9 on 2026-03-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredsubscription',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitoredsubscription',
            name='form_action',
            field=models.TextField(blank=True, default=''),
        ),
    ]
