# Generated by Django 5.2.10 on 2026-01-10 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intent_score",
                    models.FloatField(
                        help_text="Intent signal score (45% weight)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "synergy_score",
                    models.FloatField(
                        help_text="Audience/content synergy score (25% weight)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "momentum_score",
                    models.FloatField(
                        help_text="Recent activity/momentum score (20% weight)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "context_score",
                    models.FloatField(
                        help_text="Contextual relevance score (10% weight)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        help_text="Harmonic mean of weighted scores",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed explanation of score components",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("in_progress", "In Progress"),
                            ("converted", "Converted"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-final_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "accuracy_feedback",
                    models.TextField(
                        blank=True, help_text="Feedback on match accuracy", null=True
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("successful", "Successful"),
                            ("unsuccessful", "Unsuccessful"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="matching.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Feedback",
                "verbose_name_plural": "Match Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "audience_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tiny", "Tiny (< 1K)"),
                            ("small", "Small (1K - 10K)"),
                            ("medium", "Medium (10K - 100K)"),
                            ("large", "Large (100K - 1M)"),
                            ("massive", "Massive (1M+)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("audience_description", models.TextField(blank=True, null=True)),
                ("content_style", models.TextField(blank=True, null=True)),
                ("collaboration_history", models.JSONField(blank=True, null=True)),
                (
                    "enrichment_data",
                    models.JSONField(
                        blank=True,
                        help_text="Data from Clay or other enrichment APIs",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("clay", "Clay Import"),
                            ("linkedin", "LinkedIn"),
                            ("import", "Bulk Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="matching.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("user", "profile")},
        ),
    ]
