# Generated by Django 5.2.10 on 2026-01-12 20:59

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('suggested_profile_id', models.UUIDField()),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_reason', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rich_analysis', models.TextField(blank=True, null=True)),
                ('analysis_generated_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user_feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('match_context', models.JSONField(blank=True, null=True)),
                ('score_ab', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_ba', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('harmonic_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('scale_symmetry_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trust_level', models.TextField(default='legacy')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('draft_intro_clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supabase Match',
                'verbose_name_plural': 'Supabase Matches',
                'db_table': 'match_suggestions',
                'ordering': ['-harmonic_mean'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupabaseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(blank=True, null=True)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('linkedin', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('business_focus', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='Member')),
                ('service_provided', models.TextField(blank=True, null=True)),
                ('list_size', models.IntegerField(default=0)),
                ('business_size', models.TextField(blank=True, null=True)),
                ('social_reach', models.IntegerField(default=0)),
                ('role', models.TextField(default='member')),
                ('bio', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('notes', models.TextField(blank=True, null=True)),
                ('what_you_do', models.TextField(blank=True, null=True)),
                ('who_you_serve', models.TextField(blank=True, null=True)),
                ('seeking', models.TextField(blank=True, null=True)),
                ('offering', models.TextField(blank=True, null=True)),
                ('current_projects', models.TextField(blank=True, null=True)),
                ('niche', models.TextField(blank=True, null=True)),
                ('audience_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supabase Profile',
                'verbose_name_plural': 'Supabase Profiles',
                'db_table': 'profiles',
                'ordering': ['-last_active_at'],
                'managed': False,
            },
        ),
    ]
