# Generated by Django 5.2.10 on 2026-01-30 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_add_saved_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(choices=[('guest_match', 'Guest Candidate Match'), ('directory_match', 'Directory Match'), ('partner_detail', 'Partner Detail View'), ('similar_partners', 'Similar Partners')], default='directory_match', max_length=50)),
                ('was_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('was_contacted', models.BooleanField(default=False)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, help_text='The candidate being matched (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_made', to='matching.savedcandidate')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='matching.supabaseprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Recommendation',
                'verbose_name_plural': 'Partner Recommendations',
                'ordering': ['-recommended_at'],
                'indexes': [models.Index(fields=['partner', 'recommended_at'], name='matching_pa_partner_d6dec4_idx'), models.Index(fields=['partner', 'was_contacted'], name='matching_pa_partner_1877da_idx'), models.Index(fields=['user', 'recommended_at'], name='matching_pa_user_id_6c2670_idx')],
            },
        ),
    ]
