# Generated by Django 5.2.10 on 2026-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_add_partner_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrecommendation',
            name='explanation_source',
            field=models.CharField(blank=True, help_text='How the match explanation was generated: llm_verified, llm_partial, template_fallback', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partnerrecommendation',
            name='outreach_message_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerrecommendation',
            name='time_to_first_action',
            field=models.DurationField(blank=True, help_text='Time between recommendation and first view/contact', null=True),
        ),
        migrations.AddField(
            model_name='partnerrecommendation',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
