# Generated by Django 5.2.10 on 2026-02-15 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_add_match_learning_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('member_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('access_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('month', models.DateField(help_text='First day of the month this report covers')),
                ('expires_at', models.DateTimeField(help_text='When this access code stops working')),
                ('is_active', models.BooleanField(default=True)),
                ('client_profile', models.JSONField(default=dict, help_text='Client one-pager data matching DEMO_PROFILE structure')),
                ('outreach_templates', models.JSONField(default=dict, help_text='{"initial": {"title": "...", "text": "..."}, "followup": {"title": "...", "text": "..."}}')),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member Report',
                'verbose_name_plural': 'Member Reports',
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('section', models.CharField(help_text='priority, this_week, low_priority, jv_programs', max_length=20)),
                ('section_label', models.CharField(blank=True, max_length=100)),
                ('section_note', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('apply_url', models.URLField(blank=True, help_text='For JV Programs with application links')),
                ('schedule', models.URLField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('badge_style', models.CharField(default='fit', help_text='priority, fit, or warn', max_length=20)),
                ('list_size', models.CharField(blank=True, help_text='Display format: 295K, 91K', max_length=20)),
                ('audience', models.TextField(blank=True, help_text='Audience description for expanded view')),
                ('why_fit', models.TextField(blank=True)),
                ('detail_note', models.TextField(blank=True, help_text='Italic note below why-fit')),
                ('tags', models.JSONField(default=list, help_text='[{"label": "Women", "style": "fit"}, {"label": "Active JV", "style": "priority"}]')),
                ('match_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Partner',
                'verbose_name_plural': 'Report Partners',
                'ordering': ['report', 'section', 'rank'],
            },
        ),
        migrations.RenameIndex(
            model_name='matchlearningsignal',
            new_name='matching_ma_signal__e92f0f_idx',
            old_name='matching_mat_signal__cc48c6_idx',
        ),
        migrations.RenameIndex(
            model_name='matchlearningsignal',
            new_name='matching_ma_explana_a4222b_idx',
            old_name='matching_mat_explana_6f2a1e_idx',
        ),
        migrations.AlterField(
            model_name='partnerrecommendation',
            name='time_to_first_action',
            field=models.DurationField(blank=True, help_text='Time between recommendation and first contact (conversion intent)', null=True),
        ),
        migrations.AddField(
            model_name='memberreport',
            name='supabase_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_reports', to='matching.supabaseprofile'),
        ),
        migrations.AddField(
            model_name='reportpartner',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='matching.memberreport'),
        ),
        migrations.AddField(
            model_name='reportpartner',
            name='source_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_appearances', to='matching.supabaseprofile'),
        ),
    ]
