# Generated by Django 5.2.10 on 2026-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_memberreport_reportpartner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpartner',
            name='apply_url',
            field=models.TextField(blank=True, help_text='For JV Programs with application links'),
        ),
        migrations.AlterField(
            model_name='reportpartner',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportpartner',
            name='linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportpartner',
            name='schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportpartner',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
