# Generated by Django 5.2.10 on 2026-02-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_add_outreach_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('access_code', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Outreach Event',
                'verbose_name_plural': 'Outreach Events',
                'db_table': 'outreach_events',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('category', models.CharField(choices=[('idle_report', 'Idle Report'), ('score_calibration', 'Score Calibration'), ('template_friction', 'Template Friction'), ('enrichment_quality', 'Enrichment Quality'), ('partner_friction', 'Partner Friction'), ('engagement_pattern', 'Engagement Pattern'), ('section_attention', 'Section Attention'), ('intervention_verified', 'Intervention Verified'), ('intervention_pending', 'Intervention Pending')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Supporting data for the insight')),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='matching.memberreport')),
            ],
            options={
                'verbose_name': 'Analytics Insight',
                'verbose_name_plural': 'Analytics Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('weight_change', 'ISMC Weight Adjustment'), ('re_enrichment', 'Profile Re-Enrichment'), ('report_restructure', 'Report Section/Order Change'), ('template_update', 'Outreach Template Revision'), ('why_fit_upgrade', 'Why-Fit Narrative Improvement'), ('partner_swap', 'Partner Added/Removed from Report'), ('nudge_sent', 'Client Nudge/Check-in'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='What was changed and why')),
                ('baseline_metrics', models.JSONField(default=dict, help_text='Engagement metrics snapshot before intervention')),
                ('followup_metrics', models.JSONField(default=dict, help_text='Engagement metrics snapshot after measurement window')),
                ('measurement_window_days', models.IntegerField(default=14, help_text='Days to wait before measuring impact')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('impact_assessment', models.CharField(blank=True, choices=[('positive', 'Positive Impact'), ('neutral', 'No Measurable Change'), ('negative', 'Negative Impact'), ('insufficient_data', 'Insufficient Data')], max_length=20)),
                ('impact_details', models.TextField(blank=True, help_text='What changed and by how much')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(blank=True, help_text='The insight that prompted this action (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='matching.analyticsinsight')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='matching.memberreport')),
            ],
            options={
                'verbose_name': 'Analytics Intervention',
                'verbose_name_plural': 'Analytics Interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(blank=True, db_index=True, default='', help_text='SupabaseProfile UUID, or empty for report-level aggregates', max_length=40)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('avg_time_on_page_secs', models.IntegerField(default=0)),
                ('avg_scroll_depth_pct', models.IntegerField(default=0)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_visit', models.IntegerField(blank=True, null=True)),
                ('return_visit_count', models.IntegerField(default=0)),
                ('template_open_count', models.IntegerField(default=0)),
                ('template_copy_count', models.IntegerField(default=0)),
                ('card_expand_count', models.IntegerField(default=0)),
                ('avg_card_dwell_ms', models.IntegerField(default=0)),
                ('was_checked', models.BooleanField(default=False)),
                ('email_click_count', models.IntegerField(default=0)),
                ('linkedin_click_count', models.IntegerField(default=0)),
                ('schedule_click_count', models.IntegerField(default=0)),
                ('apply_click_count', models.IntegerField(default=0)),
                ('any_contact_action', models.BooleanField(default=False)),
                ('first_action_at', models.DateTimeField(blank=True, null=True)),
                ('time_to_first_action_secs', models.IntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_summaries', to='matching.memberreport')),
            ],
            options={
                'verbose_name': 'Engagement Summary',
                'verbose_name_plural': 'Engagement Summaries',
                'indexes': [models.Index(fields=['report', 'any_contact_action'], name='matching_en_report__9c5a46_idx')],
                'unique_together': {('report', 'partner_id')},
            },
        ),
    ]
