# Generated by Django 5.2.10 on 2026-02-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_add_social_media_columns'),
        ('matching', '0018_add_verification_token_and_fields'),
    ]

    operations = [
    ]
