# Generated by Django 5.2.9 on 2026-03-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0019_merge_20260228_0503'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchcostlog',
            new_name='matching_se_tool_6af450_idx',
            old_name='matching_sea_tool_created_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube',
        ),
        migrations.AddField(
            model_name='memberreport',
            name='production_issues',
            field=models.JSONField(blank=True, default=list, help_text='List of issues from last validation run'),
        ),
        migrations.AddField(
            model_name='memberreport',
            name='production_score',
            field=models.FloatField(blank=True, help_text='0-100 score from profile standard validation', null=True),
        ),
        migrations.AddField(
            model_name='memberreport',
            name='production_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('production', 'Production')], default='draft', help_text='draft = not validated; production = passed standard, ready for Keap sync', max_length=20),
        ),
        migrations.AddField(
            model_name='memberreport',
            name='production_validated_at',
            field=models.DateTimeField(blank=True, help_text='When the profile was last validated against the standard', null=True),
        ),
    ]
