# Generated by Django 5.2.9 on 2026-03-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0020_memberreport_production_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreport',
            name='production_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_remediation', 'In Remediation'), ('pipeline_restart', 'Pipeline Restart'), ('production', 'Production')], default='draft', help_text='draft = not validated; in_remediation = judge sent to pipeline stage; pipeline_restart = needs full redo; production = approved, ready for Keap sync', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfileQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, help_text='UUID for this evaluation pass', max_length=36, unique=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(help_text='0-100 quality score from Final Judge')),
                ('verdict', models.CharField(choices=[('approved', 'Approved'), ('approved_with_notes', 'Approved With Notes'), ('revision_required', 'Revision Required'), ('blocked', 'Blocked')], max_length=30)),
                ('previous_run_id', models.CharField(blank=True, max_length=36, null=True)),
                ('previous_score', models.IntegerField(blank=True, null=True)),
                ('score_delta', models.IntegerField(blank=True, help_text='Current score minus previous score', null=True)),
                ('score_history', models.JSONField(default=list, help_text='Append-only list of {run_id, score, evaluated_at, verdict}')),
                ('required_fields_passed', models.JSONField(default=list)),
                ('required_fields_failed', models.JSONField(default=list, help_text='[{field, reason, blocking}]')),
                ('recommended_fields_present', models.JSONField(default=list)),
                ('recommended_fields_missing', models.JSONField(default=list)),
                ('partner_cards_flagged', models.JSONField(default=list, help_text='[{name, issues}]')),
                ('outreach_issues', models.JSONField(default=dict, help_text='{initial: [...], followup: [...]}')),
                ('remediation_action', models.CharField(choices=[('none', 'None'), ('self_remediated', 'Self-Remediated'), ('routed_to_verification', 'Routed to Verification'), ('routed_to_research', 'Routed to Research'), ('full_restart', 'Full Restart')], default='none', max_length=30)),
                ('remediation_notes', models.TextField(blank=True)),
                ('judge_notes', models.TextField(blank=True, help_text='Institutional memory — what caused the score, what to improve')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_logs', to='matching.memberreport')),
            ],
            options={
                'verbose_name': 'Profile Quality Log',
                'verbose_name_plural': 'Profile Quality Logs',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
