# Generated by Django 5.2.9 on 2026-03-05 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0021_alter_memberreport_production_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('calibration', 'Calibration (all raters)'), ('coverage', 'Coverage (2+ raters)'), ('validation', 'Validation (holdout)')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('selection_criteria', models.JSONField(blank=True, default=dict, help_text='{"strategy": "stratified", "score_bands": [...], "tiers": [...]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Evaluation Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('access_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_evaluations', models.IntegerField(default=0)),
                ('last_evaluation_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evaluation Reviewer',
            },
        ),
        migrations.CreateModel(
            name='WeightExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('running', 'Running'), ('measured', 'Measured'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('old_weights', models.JSONField(help_text='{"intent": 0.45, "synergy": 0.25, "momentum": 0.20, "context": 0.10}')),
                ('new_weights', models.JSONField(help_text='Proposed new dimension weights')),
                ('sub_factor_changes', models.JSONField(blank=True, default=dict, help_text='Changes to sub-factor weights within dimensions')),
                ('sample_size', models.IntegerField()),
                ('reliability_alpha', models.FloatField(blank=True, help_text='Krippendorff alpha at time of analysis', null=True)),
                ('mean_quality_before', models.FloatField(blank=True, null=True)),
                ('mean_quality_after', models.FloatField(blank=True, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('regression_coefficients', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_score', models.FloatField(help_text='Harmonic mean at evaluation time')),
                ('algorithm_breakdown', models.JSONField(default=dict, help_text='Full ISMC breakdown: {intent: {score, factors}, synergy: {...}, ...}')),
                ('why_fit_narrative', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='matching.evaluationbatch')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_items_as_client', to='matching.supabaseprofile')),
                ('partner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_items_as_partner', to='matching.supabaseprofile')),
                ('report_partner', models.ForeignKey(blank=True, help_text='Link to frozen ReportPartner snapshot if from a live report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_items', to='matching.reportpartner')),
            ],
            options={
                'ordering': ['batch', 'position'],
                'unique_together': {('batch', 'client_profile', 'partner_profile')},
            },
        ),
        migrations.AddField(
            model_name='evaluationbatch',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_batches', to='matching.evaluationreviewer'),
        ),
        migrations.CreateModel(
            name='MatchEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('quick', 'Quick (~30s)'), ('detailed', 'Detailed (~2-3min)')], default='quick', max_length=10)),
                ('partnership_potential', models.IntegerField(help_text='1=Terrible, 4=Acceptable, 7=Excellent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('recommendation_actionability', models.IntegerField(help_text='1=Not actionable, 4=Ready to go', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('narrative_quality', models.IntegerField(help_text='1=Misleading, 4=Acceptable, 7=Excellent (send as-is)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('narrative_notes', models.TextField(blank=True, help_text='What the narrative got wrong or missed')),
                ('failure_wrong_audience', models.BooleanField(default=False)),
                ('failure_one_sided_value', models.BooleanField(default=False)),
                ('failure_stale_profile', models.BooleanField(default=False)),
                ('failure_missing_contact', models.BooleanField(default=False)),
                ('failure_scale_mismatch', models.BooleanField(default=False)),
                ('failure_same_niche_no_complement', models.BooleanField(default=False)),
                ('failure_data_quality', models.BooleanField(default=False)),
                ('intent_rating', models.IntegerField(blank=True, help_text='1=Wrong/Missing, 2=Weak, 3=Reasonable, 4=Strong', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('synergy_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('momentum_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('context_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('discovery_response', models.TextField(blank=True, help_text='What is the most important thing about this match the algorithm probably does not capture?')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(help_text='When the reviewer opened this evaluation')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Auto-computed from JS timer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='matching.evaluationitem')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='matching.evaluationreviewer')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['rater', '-completed_at'], name='matching_ma_rater_i_7ee83a_idx')],
                'unique_together': {('item', 'rater')},
            },
        ),
    ]
