# Generated by Django 5.2.9 on 2026-03-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0022_evaluationbatch_evaluationreviewer_weightexperiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationbatch',
            name='completion_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchevaluation',
            name='failure_timing_readiness',
            field=models.BooleanField(default=False, help_text='Timing / launch readiness mismatch — prospect not currently positioned to execute a JV'),
        ),
    ]
