"""
Shared constants for the enrichment pipeline.

Centralizes values that are referenced across multiple modules
(consolidation_task, automated_enrichment_pipeline_safe, flows, etc.).
"""

SOURCE_PRIORITY: dict[str, int] = {
    'client_confirmed': 100,
    'client_ingest': 90,
    'manual_edit': 80,
    'csv_import': 60,
    'exa_research': 50,
    'ai_research': 40,
    'apollo': 30,
    'website_scrape': 25,
    # Directory scrapers — lowest priority so enrichment overwrites
    'scraper_youtube_api': 20,
    'scraper_speakerhub': 20,
    'scraper_muncheye': 20,
    'scraper_noomii': 20,
    'scraper_udemy': 20,
    'scraper_podchaser': 20,
    'scraper_gumroad': 20,
    'scraper_substack': 20,
    'scraper_icf_coaching': 20,
    'scraper_clickbank': 20,
    'scraper_jvzoo': 20,
    'scraper_warriorplus': 20,
    'scraper_apple_podcasts': 20,
    'scraper_eventbrite': 20,
    'scraper_medium': 20,
    'scraper_summit_speakers': 20,
    'scraper_sam_gov': 20,
    'scraper_sbir': 20,
    'scraper_sec_edgar': 20,
    'scraper_usaspending': 20,
    'scraper_usaspending_recipients': 20,
    'scraper_fdic_banks': 20,
    'scraper_sam_awards': 20,
    'scraper_chambers': 20,
    'scraper_opencorporates': 20,
    'scraper_irs_exempt': 20,
    'scraper_irs_business_leagues': 20,
    'scraper_sbir_gov': 20,
    'scraper_sec_edgar_search': 20,
    'scraper_trustpilot': 20,
    'scraper_clutch_sitemap': 20,
    'scraper_coaching_federation': 20,
    'scraper_lifecoach_directory': 20,
    'scraper_crunchbase_public': 20,
    'scraper_producthunt': 20,
    'scraper_betalist': 20,
    'scraper_startupgrind': 20,
    'scraper_f6s_startups': 20,
    'scraper_techstars_portfolio': 20,
    'scraper_fivehundred_global': 20,
    'scraper_a16z_portfolio': 20,
    'scraper_association_members': 20,
    'scraper_clarity_fm': 20,
    'scraper_thumbtack_pros': 20,
    'scraper_bbb_sitemap': 20,
    'scraper_epa_echo': 20,
    'scraper_fda_devices': 20,
    'scraper_partnerstack_marketplace': 20,
    'scraper_shareasale_merchants': 20,
    'scraper_score_mentors': 20,
    'scraper_clutch_agencies': 20,
    'scraper_upwork_agencies': 20,
    'scraper_fiverr_pros': 20,
    'scraper_alignable': 20,
    'scraper_bni_members': 20,
    'scraper_toastmasters': 20,
    'scraper_meetup_organizers': 20,
    'scraper_eonetwork': 20,
    'scraper_vistage_members': 20,
    'email_list_monitor': 20,
    'unknown': 0,
}

PROFILE_STATUS_CHOICES = [
    ('Member', 'Member'),
    ('Non Member Resource', 'Non Member Resource'),
    ('Pending', 'Pending'),
    ('Prospect', 'Prospect'),
    ('Qualified', 'Qualified'),
    ('Inactive', 'Inactive'),
]

VALID_STATUSES = {choice[0] for choice in PROFILE_STATUS_CHOICES}
