# Generated by Django 5.2.10 on 2026-01-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ICP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("solo", "Solo/Freelancer"),
                            ("small", "Small (2-10 employees)"),
                            ("medium", "Medium (11-100 employees)"),
                            ("enterprise", "Enterprise (100+ employees)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pain_points",
                    models.JSONField(default=list, help_text="List of pain points"),
                ),
                ("goals", models.JSONField(default=list, help_text="List of goals")),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "decision_makers",
                    models.JSONField(
                        blank=True,
                        help_text="Information about decision makers",
                        null=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ICP",
                "verbose_name_plural": "ICPs",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PainSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("hiring", "Hiring"),
                            ("tech_change", "Technology Change"),
                            ("funding", "Funding"),
                            ("expansion", "Expansion"),
                            ("complaint", "Complaint"),
                            ("question", "Question"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("weight", models.FloatField(default=1.0)),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="List of keywords to detect"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pain Signal",
                "verbose_name_plural": "Pain Signals",
                "ordering": ["-weight", "signal_type"],
            },
        ),
        migrations.CreateModel(
            name="TransformationAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "before_state",
                    models.TextField(help_text="Where the customer starts"),
                ),
                (
                    "after_state",
                    models.TextField(help_text="Where the customer ends up"),
                ),
                ("transformation_summary", models.TextField()),
                ("key_obstacles", models.JSONField(default=list)),
                ("value_drivers", models.JSONField(default=list)),
                ("ai_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "icp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transformation_analyses",
                        to="positioning.icp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transformation Analysis",
                "verbose_name_plural": "Transformation Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
