# Generated by Django 5.2.10 on 2026-01-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icp',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-24', '18-24 years'), ('25-34', '25-34 years'), ('35-44', '35-44 years'), ('45-54', '45-54 years'), ('55-64', '55-64 years'), ('65+', '65+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='icp',
            name='customer_type',
            field=models.CharField(choices=[('b2b', 'Business (B2B)'), ('b2c', 'Consumer (B2C)')], default='b2b', max_length=10),
        ),
        migrations.AddField(
            model_name='icp',
            name='demographics',
            field=models.CharField(blank=True, help_text='e.g., "Parents with young children", "Remote workers"', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='icp',
            name='income_level',
            field=models.CharField(blank=True, choices=[('low', 'Under $30,000'), ('lower_middle', '$30,000 - $50,000'), ('middle', '$50,000 - $75,000'), ('upper_middle', '$75,000 - $100,000'), ('high', '$100,000 - $150,000'), ('affluent', '$150,000+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='icp',
            name='company_size',
            field=models.CharField(blank=True, choices=[('solo', 'Solo/Freelancer'), ('small', 'Small (2-10 employees)'), ('medium', 'Medium (11-100 employees)'), ('enterprise', 'Enterprise (100+ employees)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='icp',
            name='decision_makers',
            field=models.JSONField(blank=True, help_text='Information about decision makers (B2B) or purchase influencers (B2C)', null=True),
        ),
    ]
