# Generated by Django 5.2.10 on 2026-01-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positioning', '0002_icp_age_range_icp_customer_type_icp_demographics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMagnetConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('what_description', models.TextField(help_text='What the audience will learn/get')),
                ('why_description', models.TextField(help_text='Why they need this before buying')),
                ('format_suggestion', models.CharField(choices=[('pdf', 'PDF Guide'), ('video', 'Short Video'), ('checklist', 'Checklist'), ('template', 'Template/Swipe File'), ('quiz', 'Quiz/Assessment'), ('calculator', 'Calculator/Tool')], max_length=20)),
                ('target_problem', models.TextField(help_text='The one problem this solves')),
                ('hook', models.CharField(blank=True, max_length=300)),
                ('estimated_creation_time', models.CharField(default='3-5 hours', max_length=50)),
                ('is_selected', models.BooleanField(default=False, help_text='User selected this concept to build')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_magnets', to='positioning.transformationanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_magnets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Magnet Concept',
                'verbose_name_plural': 'Lead Magnet Concepts',
                'ordering': ['-created_at'],
            },
        ),
    ]
