# Generated by Django 5.2.10 on 2026-01-12 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positioning', '0002_icp_age_range_icp_customer_type_icp_demographics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('pre_launch', 'Pre-Launch'), ('launch_announcement', 'Launch Announcement'), ('launch_nurture', 'Launch Nurture'), ('launch_urgency', 'Urgency/Cart Close'), ('post_buyers', 'Post-Launch Buyers'), ('post_non_buyers', 'Post-Launch Non-Buyers')], max_length=30)),
                ('purpose', models.TextField()),
                ('psychology', models.CharField(max_length=100)),
                ('content_concept', models.TextField()),
                ('aha_moment', models.TextField()),
                ('vibe_authority', models.TextField()),
                ('soft_cta', models.TextField()),
                ('hook_inspirations', models.JSONField(default=list)),
                ('included_in_small', models.BooleanField(default=False)),
                ('included_in_medium', models.BooleanField(default=False)),
                ('included_in_large', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Launch Play',
                'verbose_name_plural': 'Launch Plays',
                'ordering': ['play_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('small', 'Small (12 plays, 2-3 weeks)'), ('medium', 'Medium (29 plays, 4-6 weeks)'), ('large', 'Large (54 plays, 60-90 days)')], default='medium', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positioning.transformationanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Playbook',
                'verbose_name_plural': 'Generated Playbooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('custom_content', models.TextField(blank=True)),
                ('custom_hook', models.CharField(blank=True, max_length=200)),
                ('custom_cta', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='playbook.generatedplaybook')),
                ('launch_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbook.launchplay')),
            ],
            options={
                'verbose_name': 'Generated Play',
                'verbose_name_plural': 'Generated Plays',
                'ordering': ['scheduled_date', 'launch_play__play_number'],
            },
        ),
    ]
